export const AGREGAR_LIBRO = 'AGREGAR_LIBRO';
export const AGREGAR_LIBRO_EXITO = 'AGREGAR_LIBRO_EXITO';
export const AGREGAR_LIBRO_ERROR = 'AGREGAR_LIBRO_ERROR';

export const COMENZAR_DESCARGA_LIBRO = 'COMENZAR_DESCARGA_LIBRO';
export const DESCARGA_LIBRO_EXITO = 'DESCARGAR_LIBRO_EXITO';
export const DESCARGAR_LIBRO_ERROR = 'DESCARGAR_LIBRO_ERROR';